spring:
  profiles:
    active: dev
  main:
    web-application-type: servlet
  application:
    name: db-spring-app
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=public
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 20
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
    locations: classpath:db/migrations

payments:
  products-base-url: "http://localhost:${server.port}/api/products"
  http:
    connect-timeout-ms: 1500
    read-timeout-ms: 2500

server:
  port: 8080
